### ISSUE TITLE
Crashing on simulator target 5.1 with MapKit

### ISSUE THREAD

**Issue by seanhotw** [nathankot/webstub#6]
Get the following error whenever initializing a `MKMapView` with `showsUserLocation = true` on simulator targeting 5.1.

`'uri.rb:4:in 'decode_www_form:': undefined method 'split' for nil:NilClass`

I guess Google Maps uses that method to resolve user location. It works fine on 6.0 since MKMapView uses Apple Maps and does not call the above method anymore.

Question are
1. Should fix it by checking null string?
2. Or, should not monkey patch URI class?
